spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/awstest
    username: ${DB_USER:admin}
    password: ${DB_PASS:password}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  application:
    name: aws-test

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: VIKTORNAHORNYIEXAMPLE
      secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    queue:
      url: http://localhost:4566/000000000000/
      name: sample-queue

#server:
#  port: 8089